<a href="https://colab.research.google.com/github/bhanushri123/Toxic_Comments/blob/main/ToxicComment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow


In [2]:
!pip install pandas

In [3]:
!pip install matplotlib

In [4]:
!pip install scikit-learn


In [5]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np


In [6]:
df =pd.read_csv("/content/train.csv",error_bad_lines=False, engine="python")

<ipython-input-6-907157b9301b>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df =pd.read_csv("/content/train.csv",error_bad_lines=False, engine="python")
Skipping line 9616: unexpected end of data


In [7]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [8]:
df.tail()

id                                       comment_text  \
9609  197398a3efca11e6  "\n\nPakistani Language (Urdu)\nUrdu in Persia...   
9610  197702d8e13970d7                         wikibofh reverted 3 times.   
9611  197789bf80c88999  Arjun MBT\nYou can express your opinion in the...   
9612  1978221458932c64  Asimova\nHi Ymblanter! You know that I edited ...   
9613  19783386d2d4be37  "\n\n Eastern Europe \n\nThe article says: ""F...   

      toxic  severe_toxic  obscene  threat  insult  identity_hate  
9609      0             0        0       0       0              0  
9610      0             0        0       0       0              0  
9611      0             0        0       0       0              0  
9612      0             0        0       0       0              0  
9613      0             0        0       0       0              0

In [10]:
df.iloc[4]["comment_text"]

"You, sir, are my hero. Any chance you remember what page that's on?"

In [11]:
df[df.columns[2:]].iloc[4]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 4, dtype: int64

In [12]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.5
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.0.0
blinker                          1.4
bl

In [9]:
from tensorflow.keras.layers import TextVectorization

In [32]:
TextVectorization??

In [10]:
X = df['comment_text']
Y = df[df.columns[2:]].values

In [15]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
X

0        Explanation\nWhy the edits made under my usern...
1        D'aww! He matches this background colour I'm s...
2        Hey man, I'm really not trying to edit war. It...
3        "\nMore\nI can't make any real suggestions on ...
4        You, sir, are my hero. Any chance you remember...
                               ...                        
16770    Hello.\nSorry, I take that back. You only adde...
16771    Foxhunt99, from what you say, is it not the ca...
16772    Lucille Ball \n\n I have reverted an edit you ...
16773    wow ==\n\nThanks for some of your comments.\n\...
16774    Its only 12-episode anime and as Farix previou...
Name: comment_text, Length: 16775, dtype: object

In [17]:
Y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
MAX_FEATURES = 20000
# number of words in the vocab

In [12]:
vectorizer   = TextVectorization(max_tokens = MAX_FEATURES,output_sequence_length=1800,output_mode = 'int')
# output_sequence_length this is the max input length taht we rae taking from the comments

In [13]:
X.values

array(["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Arjun MBT\nYou can express your opinion in the Arjun MBT talk page.',
       "Asimova\nHi Ymblanter! You know that I edited the articles about Kazakhstan and my criterias were appropriate to Wikipedia's one, but you deleted my articles and after this I have losted my hope to wikipedia. I started my new articles about Kazakhstan but you

In [14]:
vectorizer.adapt(X.values)

In [22]:
vectorizer.get_vocabulary()
# this gives us an array of vocabs where the position of each word tells us the number given top that word

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'are',
 'have',
 'your',
 'with',
 'if',
 'was',
 'article',
 'or',
 'but',
 'page',
 'my',
 'an',
 'by',
 'from',
 'do',
 'at',
 'about',
 'me',
 'so',
 'can',
 'wikipedia',
 'what',
 'all',
 'there',
 'has',
 'will',
 'no',
 'its',
 'would',
 'talk',
 'please',
 'one',
 'like',
 'just',
 'he',
 'they',
 'dont',
 'any',
 'which',
 'been',
 'should',
 'more',
 'other',
 'here',
 'we',
 'see',
 'his',
 'who',
 'some',
 'also',
 'im',
 'because',
 'am',
 'know',
 'think',
 'how',
 'edit',
 'why',
 'up',
 'were',
 'articles',
 'only',
 'out',
 'people',
 'then',
 'use',
 'when',
 'time',
 'may',
 'being',
 'did',
 'thanks',
 'now',
 'their',
 'them',
 'than',
 'get',
 'even',
 'go',
 'make',
 'good',
 'had',
 'information',
 'could',
 'very',
 'well',
 'want',
 'does',
 'fuck',
 'sources',
 'such',
 'way',
 'deletion',
 'pages',
 'first',
 'name',
 

In [23]:
vectorizer("Hello my name, is Bhanu")[:5]
# working of vectorizer

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([312,  29, 114,   9,   1])>

In [15]:
vectorized_text = vectorizer(X.values)

In [25]:
vectorized_text

<tf.Tensor: shape=(16775, 1800), dtype=int64, numpy=
array([[ 609,   76,    2, ...,    0,    0,    0],
       [   1,   53, 2259, ...,    0,    0,    0],
       [ 505,  440,   69, ...,    0,    0,    0],
       ...,
       [   1, 3415,    8, ...,    0,    0,    0],
       [1345,   90,   13, ...,    0,    0,    0],
       [  46,   80,    1, ...,    0,    0,    0]])>

In [46]:
# We will build a data pipeline now
# MCSHBAP map , cache,shuffle , batch , prefetch

In [16]:
dataset  = tf.data.Dataset.from_tensor_slices((vectorized_text,Y))
dataset = dataset.cache()
dataset = dataset.shuffle(16000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)


In [17]:
batch_X,batch_Y = dataset.as_numpy_iterator().next()

In [18]:
batch_Y.shape

(16, 6)

In [19]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [20]:
train_generator = dataset.as_numpy_iterator()


In [31]:
train_generator.next()

(array([[2507,    7,  394, ...,    0,    0,    0],
        [ 134,    7,   13, ...,    0,    0,    0],
        [ 166, 1351,    1, ...,    0,    0,    0],
        ...,
        [6972,   63,   20, ...,    0,    0,    0],
        [  45,   12,   24, ...,    0,    0,    0],
        [ 342,  418,  296, ...,    0,    0,    0]]),
 array([[1, 0, 1, 0, 1, 1],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [21]:
from keras.layers import Dense,LSTM,Bidirectional,Embedding,Dropout
from keras.models import Sequential,Model


In [22]:
model = Sequential()
model.add(Embedding(MAX_FEATURES+1, 32))
model.add(Bidirectional(LSTM(32, activation ='tanh')))
model.add(Dense(128, activation ='relu'))
model.add(Dense(256, activation ='relu'))
model.add(Dense(128, activation ='relu'))
model.add(Dense(6, activation ='sigmoid'))



In [23]:
model.compile(loss = 'BinaryCrossentropy',optimizer = 'Adam')

In [42]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          640032    
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                      

In [25]:
history = model.fit(train, epochs = 1,validation_data = val)

420/420 [==============================] - 766s 2s/step - loss: 0.1355 - val_loss: 0.0796


In [26]:
history.history

{'loss': [0.13547050952911377], 'val_loss': [0.07959313690662384]}

###Make Prediction


In [27]:
input_text = vectorizer("You freaking suck!")

In [28]:
batch = test.as_numpy_iterator().next()

In [29]:
res= model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 1s 945ms/step


In [31]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [30]:
res

array([[0.23487371, 0.02329318, 0.10804301, 0.01993525, 0.11896092,
        0.02595617]], dtype=float32)